#!/usr/bin/env bash
# Hyprland's own example config must not stay in place as the user's
# hyprland.lua: HyDE loads that file last, so the example overrides the theme
# (border colors, animations) and double-binds keys (HyDE-Project/HyDE#2132).

. "$(dirname -- "$0")/lib/common.sh"

# hypr_autogen.sh relies on global_fn.sh (print_log), as in install.sh.
# shellcheck source=/dev/null
if ! . "$REPO_ROOT/Scripts/global_fn.sh" 2>/dev/null ||
    ! . "$REPO_ROOT/Scripts/hypr_autogen.sh" 2>/dev/null; then
    fail "unable to source global_fn.sh and hypr_autogen.sh"
    finish
fi

type retire_autogenerated_hypr_config >/dev/null 2>&1 ||
    fail "retire_autogenerated_hypr_config is not defined in hypr_autogen.sh"
# install.sh calls it as "fn || :", which would swallow a "command not
# found" and silently do nothing, so it has to source the file, and before
# the call.
awk '
    /^if ! source "\$\{installDir\}\/hypr_autogen\.sh"; then$/ && !call { sourced = 1 }
    /retire_autogenerated_hypr_config \|\| :/ { call = 1 }
    END { exit !(sourced && call) }
' "$REPO_ROOT/Scripts/install.sh" ||
    fail "install.sh does not source hypr_autogen.sh before calling into it"

work_dir=$(mktemp -d)
trap 'rm -rf "$work_dir"' EXIT
export cacheDir="$work_dir/cache"

# Hyprland's AUTOGENERATED_PREFIX_LUA as of v0.56 (src/config/lua/
# DefaultConfig.hpp), pinned here independently of hypr_autogen.sh so a change on
# either side shows up; the leading newline is part of it.
prefix='
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

hl.config({ autogenerated = true }) -- remove this line to remove the warning

'
# The loader exactly as the v26.8.1 migration prepends it. The command
# substitution drops the heredoc's closing "end" newline and blank line, so
# they are put back.
loader=$(sed -n "/^    cat <<'LOADER'\$/,/^LOADER\$/p" "$REPO_ROOT/Scripts/migrations/v26.8.1.sh" | sed '1d;$d')
loader="$loader

"
# Stands in for <prefix>/share/hypr/hyprland.lua of the installed Hyprland.
example="$work_dir/example.lua"
printf '%s\n' '-- This is an example Hyprland Lua config file.' 'local menu        = "hyprlauncher"' 'hl.bind("XF86AudioMute", hl.dsp.exec_cmd("mute"))' >"$example"

# 0. the two copies the comparison depends on still match their sources
[ "$prefix" = "$HYPR_AUTOGEN_PREFIX" ] || fail "prefix in hypr_autogen.sh differs from Hyprland's"
case "$loader" in *"if not hyde then"*) ;; *) fail "loader not found in the v26.8.1 migration" ;; esac
[ "$loader" = "$HYDE_LUA_LOADER" ] ||
    fail "loader in hypr_autogen.sh differs from the v26.8.1 migration"
# Against the real thing where Hyprland is installed: the binary embeds the
# prefix and the example as two separate constants, so each must appear in it.
hypr_bin=$(readlink -f "$(command -v Hyprland 2>/dev/null)" 2>/dev/null) || hypr_bin=""
if [ -n "$hypr_bin" ] && installed_example=$(hypr_example_config) && command -v python3 >/dev/null; then
    printf '%s' "$HYPR_AUTOGEN_PREFIX" >"$work_dir/prefix"
    for part in "$work_dir/prefix" "$installed_example"; do
        python3 -c 'import sys; sys.exit(open(sys.argv[2], "rb").read() not in open(sys.argv[1], "rb").read())' \
            "$hypr_bin" "$part" || fail "installed Hyprland does not embed $part"
    done
else
    skip "no Hyprland with an installed example config to check the prefix against"
fi

# Stands in for HyDE's Configs/.config/hypr/hyprland.lua template.
template="$work_dir/template.lua"
printf '%s\n' '-- HyDE template' 'dofile(entry)' >"$template"

# Writes what Hyprland generates, optionally behind HyDE's loader.
gen() { { [ "${1:-}" = loader ] && printf '%s' "$loader"; printf '%s' "$prefix"; cat "$example"; } >"$target"; }

case_no=0
# Runs the function on a fresh target; sets $target, $backup and $rc.
run_case() {
    case_no=$((case_no + 1))
    target="$work_dir/$case_no/hypr/hyprland.lua"
    backup="$work_dir/$case_no/state"
    mkdir -p "$(dirname "$target")"
}
# global_fn.sh turns on errexit, so the status is caught, not left to abort.
invoke() {
    rc=0
    retire_autogenerated_hypr_config "$target" "$backup" "${1:-$example}" "${2:-$template}" >"$work_dir/out" 2>&1 || rc=$?
}
# Staged copies the swap left next to the target.
leftovers() { find "$(dirname "$target")" -maxdepth 1 -name '.hyprland.lua.*' 2>/dev/null | wc -l; }
# Replaced: the target is the template, one intact copy of the original.
replaced() {
    local what=$1 saved
    [ "$rc" -eq 0 ] || fail "$what: returned $rc"
    cmp -s "$target" "$template" || fail "$what: target is not the template"
    [ "$(backups)" -eq 1 ] || fail "$what: expected 1 backup, found $(backups)"
    saved=$(find "$backup" -type f -name hyprland.lua | head -n1)
    [ -n "$saved" ] && cmp -s "$saved" "$work_dir/expected" || fail "$what: backup missing or altered"
    [ "$(leftovers)" -eq 0 ] || fail "$what: staged copy left behind"
}
backups() { find "$backup" -type f -name hyprland.lua 2>/dev/null | wc -l; }
# Kept in place, no backup, no error: the outcome for anything not verified.
kept() {
    cmp -s "$target" "$work_dir/before" && [ "$(backups)" -eq 0 ] && [ "$rc" -eq 0 ] || fail "$1: file was touched (rc=$rc)"
}
# Applies an edit to a freshly generated file and expects it to stay.
edited() {
    local what=$1 how=$2
    run_case
    gen loader
    eval "$how"
    cp "$target" "$work_dir/before"
    invoke
    kept "$what"
}

# 1. untouched example behind the v26.8.1 loader: replaced, copy kept intact
run_case
gen loader
cp "$target" "$work_dir/expected"
invoke
replaced "example+loader"

# 2. untouched example on its own (no loader yet)
run_case
gen
cp "$target" "$work_dir/expected"
invoke
replaced "example only"

# 3. HyDE's own template: untouched, and no warning about it
run_case
cp "$REPO_ROOT/Configs/.config/hypr/hyprland.lua" "$target"
cp "$target" "$work_dir/before"
invoke
kept "HyDE template"
grep -q WARNING "$work_dir/out" && fail "HyDE template: warned about a config that is not Hyprland's"

# 4. the marker text mid-line or indented: untouched
run_case
printf '%s\n' "$loader" 'hl.bind("F1", hl.dsp.exec_cmd("echo")) -- AUTOGENERATED HYPRLAND CONFIG.' \
    '    -- AUTOGENERATED HYPRLAND CONFIG.' >"$target"
cp "$target" "$work_dir/before"
invoke
kept "marker mid-line/indented"

# 5. no file at all: nothing to do, no backup dir created
run_case
invoke
[ "$rc" -eq 0 ] || fail "missing file: returned $rc"
[ ! -e "$backup" ] || fail "missing file: backup dir created"
[ ! -e "$target" ] || fail "missing file: something was created at the target"

# 6. empty file: untouched
run_case
: >"$target"
cp "$target" "$work_dir/before"
invoke
kept "empty file"

# 7. symlink to an untouched example (dotfile manager): link and file untouched
run_case
gen
mv "$target" "$work_dir/$case_no/managed.lua"
ln -s "$work_dir/$case_no/managed.lua" "$target"
invoke
[ "$rc" -eq 0 ] && [ -L "$target" ] && [ -f "$work_dir/$case_no/managed.lua" ] ||
    fail "symlink: link or its target was moved"
[ "$(backups)" -eq 0 ] || fail "symlink: a backup was written"

# 8. dangling symlink: left alone, no error
run_case
ln -s "$work_dir/$case_no/nowhere.lua" "$target"
invoke
[ "$rc" -eq 0 ] && [ -L "$target" ] || fail "dangling symlink: not left alone (rc=$rc)"

# 9. a directory where the file should be: untouched
run_case
mkdir "$target"
invoke
[ "$rc" -eq 0 ] && [ -d "$target" ] || fail "directory at target: was touched (rc=$rc)"

# 10. dry run: reported, nothing changed
run_case
gen
cp "$target" "$work_dir/before"
flg_DryRun=1 invoke
kept "dry run"

# 11. twice in a row (same second): the second backup must not replace the first
run_case
gen
invoke
gen loader
invoke
[ "$(backups)" -eq 2 ] || fail "repeat run: expected 2 backups, found $(backups)"
[ "$(find "$backup" -type f -name hyprland.lua -exec grep -l '^if not hyde then$' {} + | wc -l)" -eq 1 ] ||
    fail "repeat run: a backup was overwritten"

# 12. backup location unusable: fail, and keep the file where it is
run_case
gen
cp "$target" "$work_dir/expected12"
: >"$backup" # a file where the backup directory should go
invoke
[ "$rc" -ne 0 ] || fail "unusable backup dir: reported success"
cmp -s "$target" "$work_dir/expected12" || fail "unusable backup dir: file was changed"
[ "$(leftovers)" -eq 0 ] || fail "unusable backup dir: staged copy left behind"

# 13-24. anything but the exact generated bytes is the user's, and stays
edited "user code before the example" 'sed -i "1i hl.config({ general = { gaps_in = 2 } })" "$target"'
edited "comment before the example" 'sed -i "1i -- my notes" "$target"'
edited "one line of the example edited" 'sed -i "s/hyprlauncher/rofi/" "$target"'
edited "line appended to the example" 'echo "hl.config({ general = { gaps_in = 2 } })" >>"$target"'
edited "comment added inside the header" 'sed -i "/^-- EDIT THIS CONFIG/a -- mine" "$target"'
edited "code before the warning line" 'sed -i "/^hl.config({ autogenerated/i hl.env(\"A\", \"1\")" "$target"'
edited "autogenerated line removed" 'sed -i "/^hl.config({ autogenerated/d" "$target"'
edited "loader edited" 'sed -i "s/dofile(entry)/dofile(entry) -- mine/" "$target"'
edited "final newline removed" 'truncate -s -1 "$target"'
edited "blank line appended" 'echo >>"$target"'
edited "CRLF line endings" 'sed -i "s/\$/\r/" "$target"'
edited "header only, example body gone" 'printf "%s" "$prefix" >"$target"'

# 25. generated by another Hyprland release than the one installed: stays, warned
run_case
gen
printf '%s\n' '-- an older example' >"$work_dir/older.lua"
cp "$target" "$work_dir/before"
invoke "$work_dir/older.lua"
kept "example from another release"
grep -q WARNING "$work_dir/out" || fail "example from another release: no warning"

# 26. no usable installed example: nothing can be verified, so the file stays
run_case
gen
cp "$target" "$work_dir/before"
invoke "$work_dir/missing.lua"
kept "installed example missing"
: >"$work_dir/empty.lua"
invoke "$work_dir/empty.lua"
kept "installed example empty"

# 27. safe mode writes the example without the header: not Hyprland's
# generated config as far as this is concerned, left alone
run_case
sed 's/"hyprlauncher"/"hyprland-run"/' "$example" >"$target"
cp "$target" "$work_dir/before"
invoke
kept "safe-mode example"

# 28-29. no usable template: fail, the example stays, no backup is made
for bad in missing empty; do
    run_case
    gen
    cp "$target" "$work_dir/before"
    [ "$bad" = empty ] && : >"$work_dir/empty-template.lua"
    invoke "" "$work_dir/$bad-template.lua"
    [ "$rc" -ne 0 ] || fail "$bad template: reported success"
    cmp -s "$target" "$work_dir/before" || fail "$bad template: example was changed"
    [ "$(backups)" -eq 0 ] || fail "$bad template: a backup was written"
done

# 30. the template cannot be staged next to the target (directory not
# writable): fail, the example stays whole, nothing is left behind
if [ "$(id -u)" -ne 0 ]; then
    run_case
    gen
    cp "$target" "$work_dir/before"
    chmod 555 "$(dirname "$target")"
    invoke
    chmod 755 "$(dirname "$target")"
    [ "$rc" -ne 0 ] || fail "unwritable target dir: reported success"
    cmp -s "$target" "$work_dir/before" || fail "unwritable target dir: example was changed"
    [ "$(leftovers)" -eq 0 ] || fail "unwritable target dir: staged copy left behind"
else
    skip "running as root: a read-only directory does not stop the swap"
fi

# 31. the template takes over the example's permissions, not mktemp's 0600
# or the template's own
run_case
gen
cp "$target" "$work_dir/expected"
chmod 640 "$target"
invoke
replaced "mode kept"
[ "$(stat -c %a "$target")" = 640 ] || fail "mode kept: target is $(stat -c %a "$target"), expected 640"

# 32. without an explicit template, the one in cloneDir is used; without a
# cloneDir either, nothing is replaced
run_case
gen
cp "$target" "$work_dir/expected"
rc=0
cloneDir="$REPO_ROOT" retire_autogenerated_hypr_config "$target" "$backup" "$example" >/dev/null 2>&1 || rc=$?
[ "$rc" -eq 0 ] && cmp -s "$target" "$REPO_ROOT/Configs/.config/hypr/hyprland.lua" ||
    fail "default template: cloneDir's template not used (rc=$rc)"
run_case
gen
cp "$target" "$work_dir/before"
rc=0
(unset cloneDir; retire_autogenerated_hypr_config "$target" "$backup" "$example") >/dev/null 2>&1 || rc=$?
[ "$rc" -ne 0 ] && cmp -s "$target" "$work_dir/before" || fail "no cloneDir: example was replaced (rc=$rc)"

# 33. install.sh no longer needs to put anything back after the deploy
grep -q 'restore_retired_hypr_config' "$REPO_ROOT/Scripts/install.sh" &&
    fail "install.sh still calls the removed restore_retired_hypr_config"

finish
